/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Room.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Room.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[52.271, 362.211, -20.871]}>
          <group position={[753.378, 263.162, -30.437]} rotation={[0, -1.571, 0]} scale={0.656}>
            <mesh geometry={nodes.Cylinder_2006.geometry} material={nodes.Cylinder_2006.material} position={[-458.729, 386.275, 14.384]} rotation={[Math.PI / 2, 0, 0]} scale={1.41} />
            <mesh geometry={nodes.Cylinder_3002.geometry} material={nodes.Cylinder_3002.material} position={[-352.58, 386.275, 14.384]} rotation={[Math.PI / 2, 0, 0]} scale={1.41} />
            <mesh geometry={nodes.Cylinder009.geometry} material={nodes.Cylinder009.material} position={[-568.406, 386.275, 14.384]} rotation={[Math.PI / 2, 0, 0]} scale={1.41} />
            <mesh geometry={nodes.Ellipse_2005.geometry} material={materials['Material.018']} position={[277.583, -45.105, 37.488]} scale={1.524} />
            <mesh geometry={nodes.Rectangle_2008.geometry} material={materials['Material.017']} position={[0, 0, -23.619]} />
            <mesh geometry={nodes.Rectangle_3007.geometry} material={materials['Material.001']} position={[0, -44.003, 5.662]} />
            <mesh geometry={nodes.Rectangle_5006.geometry} material={materials['Material.005']} position={[-288.86, 175.223, 33.087]} />
            <mesh geometry={nodes.Rectangle_6006.geometry} material={materials['Material.004']} position={[-288.86, -134.399, 33.087]} />
          </group>
          <group position={[750.168, -126.854, -719.477]}>
            <mesh geometry={nodes['book-1'].geometry} material={materials['Material.005']} position={[-42.13, -51.791, -35.072]} rotation={[-Math.PI / 2, -1.396, -Math.PI / 2]} />
            <mesh geometry={nodes['book-2'].geometry} material={materials['Material.011']} position={[70.6, 0.508, 0]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes['book-3'].geometry} material={nodes['book-3'].material} position={[45.701, -33.992, -18.418]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes['book-4'].geometry} material={materials['Material.004']} position={[5.734, -27.492, -18.418]} rotation={[-Math.PI / 2, -1.484, -Math.PI / 2]} />
          </group>
          <group position={[496.053, -235.394, -189.069]} scale={[1.008, 0.872, 1.008]}>
            <group position={[-4.931, 2.293, -71.098]} rotation={[-0.024, -0.164, -1.574]} scale={[0.74, 1.346, 1.232]}>
              <mesh geometry={nodes.Cube_4.geometry} material={nodes.Cube_4.material} position={[-0.321, 0.865, 0.42]} rotation={[0.002, 0.001, 0]} scale={[0.994, 1.008, 0.998]} />
              <mesh geometry={nodes.Cube_4001.geometry} material={materials['Material.027']} position={[-16.676, -0.273, 9.748]} rotation={[0.002, 0.001, 0]} scale={[0.994, 1.008, 0.998]} />
              <mesh geometry={nodes.Rectangle.geometry} material={nodes.Rectangle.material} position={[-22.698, 32.77, 1.793]} rotation={[0, -1.571, 0]} />
            </group>
            <mesh geometry={nodes.paper.geometry} material={materials['Material.029']} position={[121.276, 13.315, 107.056]} rotation={[-1.528, 0.007, -2.125]} scale={[1, 0.49, 1]} />
            <mesh geometry={nodes.paper_2.geometry} material={materials['Material.028']} position={[-21.383, -15.182, 12.289]} rotation={[-Math.PI / 2, 0, -1.309]} />
          </group>
          <group position={[-650.293, -551.734, -670.097]} rotation={[Math.PI, -Math.PI / 9, Math.PI]} scale={2.255}>
            <mesh geometry={nodes.Cube_2004.geometry} material={nodes.Cube_2004.material} position={[-0.693, 56.092, -1.405]} scale={0.744} />
            <mesh geometry={nodes.Cube006.geometry} material={materials['Material.011']} position={[-0.693, -0.527, -1.405]} scale={0.776} />
            <mesh geometry={nodes.Rectangle_9001.geometry} material={materials['Material.004']} position={[57.269, -20.819, 18.716]} rotation={[0, 1.571, 0]} />
          </group>
          <group position={[547.087, -552.185, -478.177]} rotation={[0, -1.484, 0]} scale={[2.255, 2.262, 2.262]}>
            <mesh geometry={nodes.Cube005.geometry} material={materials['Material.011']} position={[-0.693, -0.527, -1.405]} scale={0.776} />
            <mesh geometry={nodes.Rectangle_9.geometry} material={materials['Material.005']} position={[57.595, -29.149, -11.996]} rotation={[0, 1.571, 0]} />
          </group>
          <group position={[768.378, 351.735, 502.39]}>
            <mesh geometry={nodes.Ellipse_3002.geometry} material={materials['Material.007']} position={[-6.987, 63.6, 1.445]} rotation={[0, -1.571, 0]} scale={0.589} />
            <mesh geometry={nodes.Rectangle_5005.geometry} material={materials['Material.001']} position={[9.477, -26, 0]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.Rectangle_6005.geometry} material={nodes.Rectangle_6005.material} position={[-7.072, -31, 0]} rotation={[0, -1.571, 0]} />
          </group>
          <group position={[-256.112, -681.266, 145.269]} scale={0.955}>
            <mesh geometry={nodes.Ellipse_2006.geometry} material={materials['Material.024']} position={[0, 7.389, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.086, 1.086, 1.661]} />
            <mesh geometry={nodes.Ellipse_3003.geometry} material={materials['Material.023']} position={[0, 10.555, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.086, 1.086, 1.661]} />
            <mesh geometry={nodes.Ellipse001.geometry} material={materials['Material.023']} position={[0, -7.389, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1.086, 1.086, 1.661]} />
          </group>
          <group position={[206.325, -660.627, 519.843]}>
            <mesh geometry={nodes.Cube002.geometry} material={materials['Material.011']} position={[-0.217, 2.242, -58.31]} rotation={[-1.529, -0.026, -0.956]} />
            <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.003']} position={[4.429, -13.81, 62.481]} rotation={[0.009, -0.954, 0.002]} scale={[0.718, 0.095, 0.718]} />
            <mesh geometry={nodes.Rectangle_2002.geometry} material={materials['Material.011']} position={[10.881, 12.469, -66.44]} rotation={[-1.529, -0.026, -0.956]} />
            <mesh geometry={nodes.Rectangle_3001.geometry} material={materials['Material.005']} position={[-33.298, 13.683, -35.199]} rotation={[-1.529, -0.026, -0.956]} />
            <mesh geometry={nodes.Rectangle001.geometry} material={materials['Material.032']} position={[-0.953, 9.154, -58.098]} rotation={[-1.529, -0.026, -0.956]} />
            <mesh geometry={nodes.红色001.geometry} material={nodes.红色001.material} position={[4.429, -13.81, 62.481]} rotation={[0.009, -0.954, 0.002]} scale={[0.718, 0.095, 0.718]} />
          </group>
          <group position={[637.143, -589.389, 708.33]}>
            <group position={[6.888, 10.695, 22.417]}>
              <mesh geometry={nodes.Cube_2003.geometry} material={materials['Material.011']} rotation={[-0.59, -0.184, -0.159]} scale={0.768} />
              <mesh geometry={nodes.Ellipse_2001.geometry} material={materials['Material.005']} position={[-3.291, 7.183, 12.665]} rotation={[-0.59, -0.184, -1.73]} scale={0.768} />
            </group>
            <mesh geometry={nodes.Cube_2002.geometry} material={materials['Material.005']} position={[-1.648, -21.839, -37.694]} rotation={[-0.087, -Math.PI / 2, 0]} />
            <mesh geometry={nodes.Cube_3001.geometry} material={nodes.Cube_3001.material} position={[19.059, -84.982, 74.492]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
            <mesh geometry={nodes.Cube001.geometry} material={materials['Material.011']} position={[-8.363, -3.839, -108.492]} rotation={[0, -1.571, 0]} />
          </group>
          <group position={[551.89, -241.79, 262.583]}>
            <group position={[32.491, -9.103, -33.06]} rotation={[0, -0.175, 0]}>
              <mesh geometry={nodes.Ellipse_2003.geometry} material={nodes.Ellipse_2003.material} position={[0.763, 7.99, -24.919]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh geometry={nodes.Ellipse_3001.geometry} material={nodes.Ellipse_3001.material} position={[0.763, 7.99, 25.676]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh geometry={nodes.Rectangle_2004.geometry} material={materials['Material.002']} position={[10.5, 5.776, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.943, 1, 1]} />
              <mesh geometry={nodes.Rectangle_3003.geometry} material={materials['Material.026']} position={[1.23, 7.164, 0.5]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh geometry={nodes.Rectangle003.geometry} material={materials['Material.026']} position={[0, -5.234, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.943, 1, 1]} />
            </group>
            <group position={[-24.943, 0, 29.887]} rotation={[0.011, 0.264, 0.195]}>
              <mesh geometry={nodes.Ellipse_2002.geometry} material={nodes.Ellipse_2002.material} position={[1.174, 7.277, -24.941]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh geometry={nodes.Ellipse_3.geometry} material={nodes.Ellipse_3.material} position={[1.173, 7.277, 25.654]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh geometry={nodes.Rectangle_3002.geometry} material={materials['Material.026']} position={[1.505, 6.494, 0.485]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh geometry={nodes.Rectangle_2003.geometry} material={materials['Material.014']} position={[10.61, 5.366, -0.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.943, 1, 1]} />
              <mesh geometry={nodes.Rectangle002.geometry} material={materials['Material.011']} position={[0, -5.234, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.943, 1, 1]} />
            </group>
          </group>
          <group position={[607.171, -347.275, 688.921]} rotation={[-Math.PI / 2, 0, 0]} scale={0.781}>
            <mesh geometry={nodes.Cube.geometry} material={materials['Material.003']} position={[46.203, -124.611, 7.271]} rotation={[0, 0, -1.745]} scale={1.28} />
            <mesh geometry={nodes.Cylinder_2001.geometry} material={materials['Material.003']} position={[-89.134, -155.169, 5.275]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.28} />
            <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.003']} position={[86.557, -127.473, 7.093]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.28} />
            <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.003']} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.718, 0.095, 0.718]} />
            <mesh geometry={nodes.Rectangle_2001.geometry} material={materials['Material.005']} position={[4.535, -22.14, -42.458]} rotation={[0, 0, -Math.PI / 2]} scale={1.28} />
            <mesh geometry={nodes.红色.geometry} material={materials['Material.014']} rotation={[-1.938, -1.513, 2.724]} scale={[0.718, 0.095, 0.718]} />
          </group>
          <group position={[538.66, 77.439, -839.836]} scale={[0.718, 0.718, 0.335]}>
            <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.010']} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1, 0.283, 1]} />
            <mesh geometry={nodes.红色002.geometry} material={materials['Material.014']} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1, 0.283, 1]} />
          </group>
          <group position={[538.66, 473.743, -839.836]} scale={[1, 1, 0.467]}>
            <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.009']} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1, 0.283, 1]} />
            <mesh geometry={nodes.红色003.geometry} material={materials['Material.013']} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1, 0.283, 1]} />
          </group>
          <group position={[669.59, 132.724, 342.133]} rotation={[-3.14, Math.PI / 2, 0]} scale={-1}>
            <mesh geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} position={[93.009, 10.857, 5.557]} rotation={[Math.PI / 2, 0, 0]} scale={0.68} />
            <mesh geometry={nodes.Rectangle_5002.geometry} material={materials['Material.005']} position={[70.759, 8.845, -8.279]} scale={0.68} />
            <mesh geometry={nodes.Torus001.geometry} material={nodes.Torus001.material} position={[88.068, 7.966, 8.232]} rotation={[0, 0, 0.002]} />
          </group>
          <group position={[-144.026, -505.166, 342.19]} rotation={[0, -Math.PI / 6, 0]} scale={1.385}>
            <mesh geometry={nodes.Cube_9001.geometry} material={materials['Material.004']} position={[-2.31, 99.849, -2.38]} rotation={[Math.PI / 2, 0, Math.PI / 4]} />
          </group>
          <group position={[514.191, -201.854, -504.863]} rotation={[0, -0.671, 0]}>
            <group position={[-1.327, 89.681, -11.155]} rotation={[0, 0.671, 0]}>
              <mesh geometry={nodes.Cube_7.geometry} material={materials['Material.010']} position={[-58.971, -92.669, -139.605]} rotation={[-Math.PI, 0.671, -Math.PI / 2]} />
              <mesh geometry={nodes.Rectangle_4.geometry} material={materials['Material.002']} position={[-9.762, -82.251, 11.614]} rotation={[-1.221, -0.266, -2.195]} scale={0.836} />
              <mesh geometry={nodes.Rectangle_5.geometry} material={materials['Material.011']} position={[4.417, -66.886, -6.245]} rotation={[-1.221, -0.266, -2.195]} scale={0.836} />
              <mesh geometry={nodes.Rectangle_6.geometry} material={materials['Material.011']} position={[46.523, 45.591, -58.479]} rotation={[-0.221, -0.659, -1.713]} scale={0.836} />
              <mesh geometry={nodes.Rectangle_6001.geometry} material={materials['Material.002']} position={[51.334, 45.041, -64.534]} rotation={[-0.221, -0.659, -1.713]} scale={0.836} />
            </group>
            <mesh geometry={nodes.Cube_4002.geometry} material={materials['Material.005']} position={[0, 2.038, 0]} rotation={[-1.134, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.Cube_5.geometry} material={materials['Material.010']} position={[139.55, -46.298, -5.065]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.Cube_7002.geometry} material={materials['Material.010']} position={[-139.918, -46.298, -3.345]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.Cube_6.geometry} material={materials['Material.010']} position={[139.488, -2.988, -83.536]} rotation={[Math.PI, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.Cube_7001.geometry} material={materials['Material.010']} position={[-139.98, -2.988, -81.817]} rotation={[Math.PI, 0, -Math.PI / 2]} />
          </group>
          <group position={[515.783, -517.349, 225.324]}>
            <mesh geometry={nodes.Cube_5003.geometry} material={materials['Material.003']} position={[0.418, 0, 0]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.Ellipse_2004.geometry} material={materials['Material.011']} position={[-121.915, 128.138, 48.077]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.Rectangle004.geometry} material={materials['Material.011']} position={[-121.918, -118.659, -4.312]} rotation={[0, -1.571, 0]} />
          </group>
          <group position={[481.821, -234.983, 13.798]} rotation={[0.04, 0, -0.12]}>
            <group position={[-38.667, 10.21, 105.47]} rotation={[-0.077, 0.466, -1.597]} scale={0.837}>
              <mesh geometry={nodes.Cube003.geometry} material={materials['Material.027']} position={[0, 0, -7.358]} />
              <mesh geometry={nodes.Rectangle_2005.geometry} material={materials['Material.025']} position={[-1.204, -0.119, 8.505]} />
              <mesh geometry={nodes.Rectangle_3004.geometry} material={materials['Material.025']} position={[-1.204, -0.119, 15.358]} />
            </group>
            <group position={[-111.237, 1.413, -9.913]} rotation={[3.074, -0.728, 1.602]} scale={0.837}>
              <mesh geometry={nodes.Cube004.geometry} material={materials['Material.027']} position={[0, 0, -7.358]} />
              <mesh geometry={nodes.Rectangle_2006.geometry} material={materials['Material.025']} position={[-1.204, -0.119, 8.505]} />
              <mesh geometry={nodes.Rectangle_3005.geometry} material={materials['Material.025']} position={[-1.204, -0.119, 15.358]} />
            </group>
            <mesh geometry={nodes.Cylinder_2002.geometry} material={nodes.Cylinder_2002.material} position={[-108.141, 0.251, -37.353]} rotation={[-1.659, 0.023, -0.755]} scale={1.195} />
            <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[-14.86, 11.427, 113.341]} rotation={[-1.659, 0.023, -1.191]} scale={1.195} />
            <mesh geometry={nodes.line.geometry} material={materials['Material.023']} position={[-192.136, -93.046, -3.893]} rotation={[-0.352, -1.365, 2.8]} scale={-2.04} />
            <mesh geometry={nodes.Torus.geometry} material={materials['Material.025']} position={[-46.357, 3.62, 28.469]} rotation={[-1.659, 0.023, -2.588]} scale={[1.261, 1.195, 1.195]} />
          </group>
          <group position={[-558.49, -331.427, -541.533]} rotation={[-0.397, 0.179, 0.232]} scale={1.092}>
            <mesh geometry={nodes.Shape_2.geometry} material={materials['Material.012']} position={[-82.002, -132.423, -38.903]} />
            <mesh geometry={nodes.Shape_3.geometry} material={materials['Material.002']} position={[-25.829, -106.067, 3.571]} />
            <mesh geometry={nodes.Shape_4.geometry} material={materials['Material.002']} position={[-27.707, -266.659, 4.484]} />
          </group>
          <group position={[-316.868, -107.967, -585.195]} rotation={[0, 1.222, 0]} scale={1.673}>
            <mesh geometry={nodes.Cube_6001.geometry} material={materials['Material.006']} position={[47.951, -248.792, -37.784]} rotation={[0, 0.698, 0]} />
            <mesh geometry={nodes.Cube_7004.geometry} material={materials['Material.006']} position={[-51.785, 282.284, 41.486]} rotation={[0, 0.698, Math.PI / 3]} />
            <mesh geometry={nodes.Cylinder_2005.geometry} material={nodes.Cylinder_2005.material} position={[49.132, -333.684, -36.386]} rotation={[0, 0.698, 0]} />
            <mesh geometry={nodes.Sphere_2.geometry} material={nodes.Sphere_2.material} position={[-62.278, 256.697, 49.132]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[689.315, -31.839, 9.389]} scale={[1, 0.815, 1]}>
            <mesh geometry={nodes.Rectangle_10.geometry} material={nodes.Rectangle_10.material} position={[-0.18, -4.677, 17.569]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.Rectangle_11.geometry} material={nodes.Rectangle_11.material} position={[-0.18, -4.677, 51.67]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.Rectangle_12.geometry} material={nodes.Rectangle_12.material} position={[-0.18, -4.677, 85.376]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.Rectangle_13.geometry} material={nodes.Rectangle_13.material} position={[-0.18, -4.677, 118.965]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.Rectangle_14.geometry} material={nodes.Rectangle_14.material} position={[-0.18, -4.677, 153.06]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.Rectangle_5003.geometry} material={nodes.Rectangle_5003.material} position={[-0.18, -4.677, -150.997]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.Rectangle_6003.geometry} material={nodes.Rectangle_6003.material} position={[-0.18, -4.677, -117.145]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.Rectangle_7001.geometry} material={nodes.Rectangle_7001.material} position={[-0.18, -4.677, -83.508]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.Rectangle_8.geometry} material={nodes.Rectangle_8.material} position={[-0.18, -4.677, -49.149]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.Rectangle_9002.geometry} material={nodes.Rectangle_9002.material} position={[-0.18, -4.677, -16.448]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.Rectangle005.geometry} material={materials['Material.018']} position={[6.777, 0.845, -0.043]} rotation={[0, -1.571, 0]} scale={[1, 1.227, 1]} />
          </group>
          <group position={[-646.413, -273.809, -835.297]}>
            <mesh geometry={nodes.Rectangle_3008.geometry} material={materials['Material.005']} position={[0, 124.12, -9.513]} scale={0.887} />
            <mesh geometry={nodes.Rectangle006.geometry} material={materials['Material.011']} position={[1.429, 125.828, 10.85]} scale={0.887} />
          </group>
          <group position={[-646.413, 304.542, -835.297]}>
            <mesh geometry={nodes.Rectangle_3009.geometry} material={materials['Material.005']} position={[0, 0, -11.729]} scale={0.887} />
            <mesh geometry={nodes.Rectangle007.geometry} material={materials['Material.007']} position={[1.429, 0, 10.85]} scale={0.887} />
            <mesh geometry={nodes.Shape_2001.geometry} material={materials['Material.003']} position={[-146.075, -53.566, 11.729]} scale={1.429} />
            <mesh geometry={nodes.Shape_3001.geometry} material={materials['Material.003']} position={[25.296, 20.093, 11.729]} scale={1.429} />
            <mesh geometry={nodes.Shape_4001.geometry} material={materials['Material.003']} position={[36.168, 28.759, 11.729]} scale={1.429} />
          </group>
          <group position={[822.913, 129.717, 706.066]}>
            <mesh geometry={nodes.Rectangle_3010.geometry} material={materials['Material.004']} position={[9.484, -5.72, 0]} rotation={[0, -1.571, 0]} scale={0.54} />
            <mesh geometry={nodes.Rectangle008.geometry} material={materials['Material.011']} position={[-9.791, -5.72, 0]} rotation={[0, -1.571, 0]} scale={0.507} />
            <mesh geometry={nodes.Shape_2002.geometry} material={materials['Material.020']} position={[-25.651, 71.309, -20.633]} rotation={[0, -1.571, 0]} scale={0.691} />
            <mesh geometry={nodes.Shape_3002.geometry} material={materials['Material.010']} position={[-23.225, 65.88, -34.493]} rotation={[0, -1.571, 0]} scale={0.691} />
            <mesh geometry={nodes.Shape_4002.geometry} material={materials['Material.019']} position={[-11.048, 170, -105.415]} rotation={[0, -1.571, 0]} scale={0.691} />
            <mesh geometry={nodes.Shape_5.geometry} material={nodes.Shape_5.material} position={[-19.985, 49.696, -28.411]} rotation={[0, -1.571, 0]} scale={0.691} />
            <mesh geometry={nodes.Shape_7.geometry} material={nodes.Shape_7.material} position={[-16.536, -108.778, 67.954]} rotation={[0, -1.571, 0]} scale={0.691} />
            <mesh geometry={nodes.Shape_8.geometry} material={nodes.Shape_8.material} position={[-14.086, -91.412, 72.722]} rotation={[0, -1.571, 0]} scale={0.691} />
          </group>
          <group position={[639.711, -96.336, 448.951]} rotation={[0, -Math.PI / 3, 0]} scale={1.521}>
            <mesh geometry={nodes.Cube_2001.geometry} material={materials['Material.030']} position={[-1.091, -85.486, 0]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Cube_3.geometry} material={materials['Material.013']} position={[7.824, 68.332, -2.539]} rotation={[0, 0, 0.047]} />
            <mesh geometry={nodes.Cube_4003.geometry} material={materials['Material.008']} position={[5.492, 46.53, -1.342]} rotation={[-0.052, 0.007, -0.125]} />
            <mesh geometry={nodes.Cube_5001.geometry} material={materials['Material.008']} position={[-9.044, 12.187, 0.73]} rotation={[-Math.PI, 0, 2.705]} />
          </group>
          <group position={[121.459, -340.722, -663.834]} rotation={[-Math.PI, 0.32, -Math.PI]} scale={[1.842, 1.829, 2.184]}>
            <mesh geometry={nodes.Cylinder_2003.geometry} material={materials['Material.008']} position={[-2.931, -59.751, 3.721]} />
            <mesh geometry={nodes.Cylinder_3001.geometry} material={materials['Material.008']} position={[29.751, 19.92, 9.976]} rotation={[0.096, -0.435, 0.041]} />
            <mesh geometry={nodes.Cylinder005.geometry} material={materials['Material.005']} position={[-0.962, -138.995, -2.716]} />
          </group>
          <group position={[740.414, -210.108, -370.652]} rotation={[0, -1.039, 0]} scale={1.039}>
            <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.031']} position={[0, -4.014, -4.083]} />
            <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.011']} position={[27.389, 6.265, 30.127]} rotation={[Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.004']} position={[15.681, -26.495, 29.773]} rotation={[Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Cylinder_3.geometry} material={materials['Material.005']} position={[34.861, -26.495, 29.773]} rotation={[Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Rectangle_5001.geometry} material={materials['Material.011']} position={[-19.573, -8.381, 30.127]} scale={[1.073, 0.857, 0.857]} />
            <mesh geometry={nodes.Rectangle_6002.geometry} material={nodes.Rectangle_6002.material} position={[-29.521, -26.641, 27.861]} scale={[1.004, 0.857, 0.857]} />
            <mesh geometry={nodes.Rectangle_7.geometry} material={materials['Material.007']} position={[-13.239, -26.641, 27.861]} scale={[1.004, 0.857, 0.857]} />
            <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.004']} position={[27.367, 6.455, 33.708]} />
          </group>
          <group position={[566.558, -470.164, -221.281]} scale={0.702}>
            <group position={[0, 230.159, 109]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Mesh_159.geometry} material={materials['Material.004']} />
              <mesh geometry={nodes.Mesh_159_1.geometry} material={materials['Material.012']} />
              <mesh geometry={nodes.Mesh_159_2.geometry} material={materials['Material.015']} />
            </group>
          </group>
          <group position={[619.152, -528.407, 711.601]} scale={[1, 1, 0.934]}>
            <mesh geometry={nodes.Cube_12.geometry} material={materials['Material.003']} position={[154.213, -149.506, 4.453]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1.324, 1, 1]} />
            <mesh geometry={nodes.Cube_5002.geometry} material={materials['Material.005']} position={[0, 131.006, -3.463]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          </group>
          <group position={[694.147, 306.445, -410.953]} rotation={[0, -1.571, 0]}>
            <mesh geometry={nodes.Ellipse.geometry} material={materials['Material.007']} position={[-1.096, 90.631, 8.529]} />
            <mesh geometry={nodes.Rectangle_2007.geometry} material={materials['Material.005']} position={[0, 0, -15.529]} />
            <mesh geometry={nodes.Rectangle_3006.geometry} material={materials['Material.001']} position={[-0.082, 90.215, 0.091]} scale={[0.963, 1, 1]} />
            <mesh geometry={nodes.Rectangle_5004.geometry} material={nodes.Rectangle_5004.material} position={[-54.412, -63.896, 1.415]} scale={[0.963, 1, 1]} />
            <mesh geometry={nodes.Rectangle_6004.geometry} material={nodes.Rectangle_6004.material} position={[-81.37, -111.262, 1.415]} scale={[0.963, 1, 1]} />
            <mesh geometry={nodes.Rectangle_7002.geometry} material={nodes.Rectangle_7002.material} position={[-17.343, -156.403, 1.415]} scale={[0.963, 1, 1]} />
            <mesh geometry={nodes.Triangle.geometry} material={nodes.Triangle.material} position={[4.984, 90.898, 9.529]} rotation={[0, 0, -Math.PI / 2]} />
          </group>
          <group position={[-43.228, 255.289, -833.016]}>
            <mesh geometry={nodes.Cube_4004.geometry} material={materials['Material.004']} position={[0.635, 0.937, -10.808]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.Cube_5004.geometry} material={materials['Material.005']} position={[1.686, 105.584, 0]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.窗户.geometry} material={nodes.窗户.material} position={[0, -198.5, 9.159]} rotation={[0, 0, -Math.PI / 2]} />
          </group>
          <mesh geometry={nodes.Ellipse_2.geometry} material={materials['Material.011']} position={[-517.765, -484.515, -468.851]} rotation={[-0.401, 0.175, 0.227]} />
          <mesh geometry={nodes.icon.geometry} material={nodes.icon.material} position={[715.693, -104.429, 824.957]} rotation={[-0.342, -1.138, -1.081]} />
          <mesh geometry={nodes.Sphere.geometry} material={materials['Material.022']} position={[191.521, -579.485, -386.943]} rotation={[0, -1.571, 0]} />
        </group>
        <mesh geometry={nodes.Walls.geometry} material={materials['Material.002']} position={[33.168, -323.764, -23.547]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.702} />
      </group>
    </group>
  )
}

useGLTF.preload('/Room.glb')
